apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab/engineering/products/api_security/devops/test-project.git'
    targetRevision: test-argo
    path: charts/nginx1
    helm:
      releaseName: nginx1
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab/engineering/products/api_security/devops/test-project.git'
    targetRevision: test-argo
    path: charts/nginx2
    helm:
      releaseName: nginx2
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
